-- Drop the current schema baseline while leaving schema_migrations intact for the migration runner.

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.webhook_delivery DROP CONSTRAINT IF EXISTS webhook_delivery_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.webhook_delivery DROP CONSTRAINT IF EXISTS webhook_delivery_trigger_id_fkey;
ALTER TABLE IF EXISTS ONLY public.webhook_delivery DROP CONSTRAINT IF EXISTS webhook_delivery_replayed_from_delivery_id_fkey;
ALTER TABLE IF EXISTS ONLY public.webhook_delivery DROP CONSTRAINT IF EXISTS webhook_delivery_autopilot_run_id_fkey;
ALTER TABLE IF EXISTS ONLY public.webhook_delivery DROP CONSTRAINT IF EXISTS webhook_delivery_autopilot_id_fkey;
ALTER TABLE IF EXISTS ONLY public.task_usage DROP CONSTRAINT IF EXISTS task_usage_task_id_fkey;
ALTER TABLE IF EXISTS ONLY public.task_trace_event DROP CONSTRAINT IF EXISTS task_trace_event_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.task_trace_event DROP CONSTRAINT IF EXISTS task_trace_event_trigger_comment_id_fkey;
ALTER TABLE IF EXISTS ONLY public.task_trace_event DROP CONSTRAINT IF EXISTS task_trace_event_task_id_fkey;
ALTER TABLE IF EXISTS ONLY public.task_trace_event DROP CONSTRAINT IF EXISTS task_trace_event_squad_id_fkey;
ALTER TABLE IF EXISTS ONLY public.task_trace_event DROP CONSTRAINT IF EXISTS task_trace_event_runtime_id_fkey;
ALTER TABLE IF EXISTS ONLY public.task_trace_event DROP CONSTRAINT IF EXISTS task_trace_event_project_id_fkey;
ALTER TABLE IF EXISTS ONLY public.task_trace_event DROP CONSTRAINT IF EXISTS task_trace_event_issue_id_fkey;
ALTER TABLE IF EXISTS ONLY public.task_trace_event DROP CONSTRAINT IF EXISTS task_trace_event_chat_session_id_fkey;
ALTER TABLE IF EXISTS ONLY public.task_trace_event DROP CONSTRAINT IF EXISTS task_trace_event_autopilot_run_id_fkey;
ALTER TABLE IF EXISTS ONLY public.task_trace_event DROP CONSTRAINT IF EXISTS task_trace_event_agent_id_fkey;
ALTER TABLE IF EXISTS ONLY public.task_token DROP CONSTRAINT IF EXISTS task_token_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.task_token DROP CONSTRAINT IF EXISTS task_token_user_id_fkey;
ALTER TABLE IF EXISTS ONLY public.task_token DROP CONSTRAINT IF EXISTS task_token_task_id_fkey;
ALTER TABLE IF EXISTS ONLY public.task_token DROP CONSTRAINT IF EXISTS task_token_agent_id_fkey;
ALTER TABLE IF EXISTS ONLY public.task_message DROP CONSTRAINT IF EXISTS task_message_task_id_fkey;
ALTER TABLE IF EXISTS ONLY public.squad DROP CONSTRAINT IF EXISTS squad_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.squad_sop_step_event DROP CONSTRAINT IF EXISTS squad_sop_step_event_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.squad_sop_step_event DROP CONSTRAINT IF EXISTS squad_sop_step_event_task_id_fkey;
ALTER TABLE IF EXISTS ONLY public.squad_sop_step_event DROP CONSTRAINT IF EXISTS squad_sop_step_event_squad_id_fkey;
ALTER TABLE IF EXISTS ONLY public.squad_sop_step_event DROP CONSTRAINT IF EXISTS squad_sop_step_event_run_id_fkey;
ALTER TABLE IF EXISTS ONLY public.squad_sop_step_event DROP CONSTRAINT IF EXISTS squad_sop_step_event_issue_id_fkey;
ALTER TABLE IF EXISTS ONLY public.squad_sop_run DROP CONSTRAINT IF EXISTS squad_sop_run_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.squad_sop_run DROP CONSTRAINT IF EXISTS squad_sop_run_squad_id_fkey;
ALTER TABLE IF EXISTS ONLY public.squad_sop_run DROP CONSTRAINT IF EXISTS squad_sop_run_leader_task_id_fkey;
ALTER TABLE IF EXISTS ONLY public.squad_sop_run DROP CONSTRAINT IF EXISTS squad_sop_run_issue_id_fkey;
ALTER TABLE IF EXISTS ONLY public.squad_member DROP CONSTRAINT IF EXISTS squad_member_squad_id_fkey;
ALTER TABLE IF EXISTS ONLY public.squad DROP CONSTRAINT IF EXISTS squad_leader_id_fkey;
ALTER TABLE IF EXISTS ONLY public.skill DROP CONSTRAINT IF EXISTS skill_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.skill_file DROP CONSTRAINT IF EXISTS skill_file_skill_id_fkey;
ALTER TABLE IF EXISTS ONLY public.skill DROP CONSTRAINT IF EXISTS skill_created_by_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_library_version DROP CONSTRAINT IF EXISTS prompt_library_version_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_library_version DROP CONSTRAINT IF EXISTS prompt_library_version_source_candidate_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_library_version DROP CONSTRAINT IF EXISTS prompt_library_version_prompt_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_library_version DROP CONSTRAINT IF EXISTS prompt_library_version_project_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_library_version DROP CONSTRAINT IF EXISTS prompt_library_version_created_by_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_library_trial DROP CONSTRAINT IF EXISTS prompt_library_trial_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_library_trial DROP CONSTRAINT IF EXISTS prompt_library_trial_version_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_library_trial DROP CONSTRAINT IF EXISTS prompt_library_trial_task_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_library_trial DROP CONSTRAINT IF EXISTS prompt_library_trial_prompt_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_library_trial DROP CONSTRAINT IF EXISTS prompt_library_trial_created_by_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_library_trial DROP CONSTRAINT IF EXISTS prompt_library_trial_chat_session_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_library_trial DROP CONSTRAINT IF EXISTS prompt_library_trial_agent_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_library_item DROP CONSTRAINT IF EXISTS prompt_library_item_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_library_item DROP CONSTRAINT IF EXISTS prompt_library_item_project_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_library_item DROP CONSTRAINT IF EXISTS prompt_library_item_created_by_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_trial DROP CONSTRAINT IF EXISTS prompt_evaluation_trial_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_trial DROP CONSTRAINT IF EXISTS prompt_evaluation_trial_run_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_trial DROP CONSTRAINT IF EXISTS prompt_evaluation_trial_asset_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_test_suite_case DROP CONSTRAINT IF EXISTS prompt_evaluation_test_suite_case_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_test_suite_case DROP CONSTRAINT IF EXISTS prompt_evaluation_test_suite_case_test_suite_asset_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_test_suite_case DROP CONSTRAINT IF EXISTS prompt_evaluation_test_suite_case_created_by_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_test_suite_case DROP CONSTRAINT IF EXISTS prompt_evaluation_test_suite_case_case_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_run DROP CONSTRAINT IF EXISTS prompt_evaluation_run_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_run DROP CONSTRAINT IF EXISTS prompt_evaluation_run_task_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_run DROP CONSTRAINT IF EXISTS prompt_evaluation_run_runtime_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_run DROP CONSTRAINT IF EXISTS prompt_evaluation_run_reviewed_by_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_run DROP CONSTRAINT IF EXISTS prompt_evaluation_run_prompt_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_run DROP CONSTRAINT IF EXISTS prompt_evaluation_run_created_by_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_run DROP CONSTRAINT IF EXISTS prompt_evaluation_run_chat_session_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_run DROP CONSTRAINT IF EXISTS prompt_evaluation_run_asset_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_run DROP CONSTRAINT IF EXISTS prompt_evaluation_run_agent_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_optimization_candidate DROP CONSTRAINT IF EXISTS prompt_evaluation_optimization_candidate_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_optimization_candidate DROP CONSTRAINT IF EXISTS prompt_evaluation_optimization_candidate_run_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_optimization_candidate DROP CONSTRAINT IF EXISTS prompt_evaluation_optimization_candidate_prompt_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_optimization_candidate DROP CONSTRAINT IF EXISTS prompt_evaluation_optimization_candidate_created_by_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_optimization_candidate DROP CONSTRAINT IF EXISTS prompt_evaluation_optimization_candidate_asset_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_optimization_candidate DROP CONSTRAINT IF EXISTS prompt_evaluation_optimization_candida_published_prompt_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_evidence_snapshot DROP CONSTRAINT IF EXISTS prompt_evaluation_evidence_snapshot_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_evidence_snapshot DROP CONSTRAINT IF EXISTS prompt_evaluation_evidence_snapshot_run_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_evidence_snapshot DROP CONSTRAINT IF EXISTS prompt_evaluation_evidence_snapshot_created_by_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_dimension_score DROP CONSTRAINT IF EXISTS prompt_evaluation_dimension_score_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_dimension_score DROP CONSTRAINT IF EXISTS prompt_evaluation_dimension_score_run_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_dimension_score DROP CONSTRAINT IF EXISTS prompt_evaluation_dimension_score_prompt_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_dimension_score DROP CONSTRAINT IF EXISTS prompt_evaluation_dimension_score_asset_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_dataset_version DROP CONSTRAINT IF EXISTS prompt_evaluation_dataset_version_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_dataset_version_row DROP CONSTRAINT IF EXISTS prompt_evaluation_dataset_version_row_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_dataset_version_row DROP CONSTRAINT IF EXISTS prompt_evaluation_dataset_version_row_source_row_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_dataset_version_row DROP CONSTRAINT IF EXISTS prompt_evaluation_dataset_version_row_dataset_version_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_dataset_version_row DROP CONSTRAINT IF EXISTS prompt_evaluation_dataset_version_row_dataset_asset_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_dataset_version_row DROP CONSTRAINT IF EXISTS prompt_evaluation_dataset_version_row_case_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_dataset_version DROP CONSTRAINT IF EXISTS prompt_evaluation_dataset_version_dataset_asset_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_dataset_version DROP CONSTRAINT IF EXISTS prompt_evaluation_dataset_version_created_by_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_dataset_row DROP CONSTRAINT IF EXISTS prompt_evaluation_dataset_row_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_dataset_row DROP CONSTRAINT IF EXISTS prompt_evaluation_dataset_row_dataset_asset_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_dataset_row DROP CONSTRAINT IF EXISTS prompt_evaluation_dataset_row_created_by_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_dataset_row DROP CONSTRAINT IF EXISTS prompt_evaluation_dataset_row_case_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_case DROP CONSTRAINT IF EXISTS prompt_evaluation_case_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_case DROP CONSTRAINT IF EXISTS prompt_evaluation_case_prompt_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_case_operation DROP CONSTRAINT IF EXISTS prompt_evaluation_case_operation_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_case_operation DROP CONSTRAINT IF EXISTS prompt_evaluation_case_operation_created_by_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_case_operation DROP CONSTRAINT IF EXISTS prompt_evaluation_case_operation_asset_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_case DROP CONSTRAINT IF EXISTS prompt_evaluation_case_created_by_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_case DROP CONSTRAINT IF EXISTS prompt_evaluation_case_asset_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_case_assertion DROP CONSTRAINT IF EXISTS prompt_evaluation_case_assertion_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_case_assertion DROP CONSTRAINT IF EXISTS prompt_evaluation_case_assertion_case_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_case_assertion DROP CONSTRAINT IF EXISTS prompt_evaluation_case_assertion_asset_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_asset DROP CONSTRAINT IF EXISTS prompt_evaluation_asset_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_asset DROP CONSTRAINT IF EXISTS prompt_evaluation_asset_prompt_id_fkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_asset DROP CONSTRAINT IF EXISTS prompt_evaluation_asset_created_by_fkey;
ALTER TABLE IF EXISTS ONLY public.project DROP CONSTRAINT IF EXISTS project_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.project_resource DROP CONSTRAINT IF EXISTS project_resource_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.project_resource DROP CONSTRAINT IF EXISTS project_resource_project_id_fkey;
ALTER TABLE IF EXISTS ONLY public.project DROP CONSTRAINT IF EXISTS project_owner_id_fkey;
ALTER TABLE IF EXISTS ONLY public.pinned_item DROP CONSTRAINT IF EXISTS pinned_item_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.pinned_item DROP CONSTRAINT IF EXISTS pinned_item_user_id_fkey;
ALTER TABLE IF EXISTS ONLY public.personal_access_token DROP CONSTRAINT IF EXISTS personal_access_token_user_id_fkey;
ALTER TABLE IF EXISTS ONLY public.notification_preference DROP CONSTRAINT IF EXISTS notification_preference_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.notification_preference DROP CONSTRAINT IF EXISTS notification_preference_user_id_fkey;
ALTER TABLE IF EXISTS ONLY public.member DROP CONSTRAINT IF EXISTS member_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.member DROP CONSTRAINT IF EXISTS member_user_id_fkey;
ALTER TABLE IF EXISTS ONLY public.lark_user_binding DROP CONSTRAINT IF EXISTS lark_user_binding_member_fk;
ALTER TABLE IF EXISTS ONLY public.lark_user_binding DROP CONSTRAINT IF EXISTS lark_user_binding_installation_fk;
ALTER TABLE IF EXISTS ONLY public.lark_outbound_card_message DROP CONSTRAINT IF EXISTS lark_outbound_card_message_task_id_fkey;
ALTER TABLE IF EXISTS ONLY public.lark_outbound_card_message DROP CONSTRAINT IF EXISTS lark_outbound_card_message_chat_session_id_fkey;
ALTER TABLE IF EXISTS ONLY public.lark_installation DROP CONSTRAINT IF EXISTS lark_installation_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.lark_installation DROP CONSTRAINT IF EXISTS lark_installation_installer_user_id_fkey;
ALTER TABLE IF EXISTS ONLY public.lark_installation DROP CONSTRAINT IF EXISTS lark_installation_agent_id_fkey;
ALTER TABLE IF EXISTS ONLY public.lark_inbound_message_dedup DROP CONSTRAINT IF EXISTS lark_inbound_message_dedup_installation_id_fkey;
ALTER TABLE IF EXISTS ONLY public.lark_inbound_audit DROP CONSTRAINT IF EXISTS lark_inbound_audit_installation_id_fkey;
ALTER TABLE IF EXISTS ONLY public.lark_chat_session_binding DROP CONSTRAINT IF EXISTS lark_chat_session_binding_installation_id_fkey;
ALTER TABLE IF EXISTS ONLY public.lark_chat_session_binding DROP CONSTRAINT IF EXISTS lark_chat_session_binding_chat_session_id_fkey;
ALTER TABLE IF EXISTS ONLY public.lark_binding_token DROP CONSTRAINT IF EXISTS lark_binding_token_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.lark_binding_token DROP CONSTRAINT IF EXISTS lark_binding_token_installation_id_fkey;
ALTER TABLE IF EXISTS ONLY public.issue DROP CONSTRAINT IF EXISTS issue_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.issue_to_label DROP CONSTRAINT IF EXISTS issue_to_label_label_id_fkey;
ALTER TABLE IF EXISTS ONLY public.issue_to_label DROP CONSTRAINT IF EXISTS issue_to_label_issue_id_fkey;
ALTER TABLE IF EXISTS ONLY public.issue_subscriber DROP CONSTRAINT IF EXISTS issue_subscriber_issue_id_fkey;
ALTER TABLE IF EXISTS ONLY public.issue_reaction DROP CONSTRAINT IF EXISTS issue_reaction_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.issue_reaction DROP CONSTRAINT IF EXISTS issue_reaction_issue_id_fkey;
ALTER TABLE IF EXISTS ONLY public.issue_pull_request DROP CONSTRAINT IF EXISTS issue_pull_request_pull_request_id_fkey;
ALTER TABLE IF EXISTS ONLY public.issue_pull_request DROP CONSTRAINT IF EXISTS issue_pull_request_issue_id_fkey;
ALTER TABLE IF EXISTS ONLY public.issue DROP CONSTRAINT IF EXISTS issue_project_id_fkey;
ALTER TABLE IF EXISTS ONLY public.issue DROP CONSTRAINT IF EXISTS issue_parent_issue_id_fkey;
ALTER TABLE IF EXISTS ONLY public.issue DROP CONSTRAINT IF EXISTS issue_owner_id_fkey;
ALTER TABLE IF EXISTS ONLY public.issue_label DROP CONSTRAINT IF EXISTS issue_label_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.issue_dependency DROP CONSTRAINT IF EXISTS issue_dependency_issue_id_fkey;
ALTER TABLE IF EXISTS ONLY public.issue_dependency DROP CONSTRAINT IF EXISTS issue_dependency_depends_on_issue_id_fkey;
ALTER TABLE IF EXISTS ONLY public.inbox_item DROP CONSTRAINT IF EXISTS inbox_item_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.inbox_item DROP CONSTRAINT IF EXISTS inbox_item_issue_id_fkey;
ALTER TABLE IF EXISTS ONLY public.github_pull_request DROP CONSTRAINT IF EXISTS github_pull_request_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.github_pull_request_check_suite DROP CONSTRAINT IF EXISTS github_pull_request_check_suite_pr_id_fkey;
ALTER TABLE IF EXISTS ONLY public.github_installation DROP CONSTRAINT IF EXISTS github_installation_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.github_installation DROP CONSTRAINT IF EXISTS github_installation_connected_by_id_fkey;
ALTER TABLE IF EXISTS ONLY public.feedback DROP CONSTRAINT IF EXISTS feedback_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.feedback DROP CONSTRAINT IF EXISTS feedback_user_id_fkey;
ALTER TABLE IF EXISTS ONLY public.external_credential_profile DROP CONSTRAINT IF EXISTS external_credential_profile_user_id_fkey;
ALTER TABLE IF EXISTS ONLY public.daemon_token DROP CONSTRAINT IF EXISTS daemon_token_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.daemon_connection DROP CONSTRAINT IF EXISTS daemon_connection_agent_id_fkey;
ALTER TABLE IF EXISTS ONLY public.comment DROP CONSTRAINT IF EXISTS comment_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.comment_reaction DROP CONSTRAINT IF EXISTS comment_reaction_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.comment_reaction DROP CONSTRAINT IF EXISTS comment_reaction_comment_id_fkey;
ALTER TABLE IF EXISTS ONLY public.comment DROP CONSTRAINT IF EXISTS comment_parent_id_fkey;
ALTER TABLE IF EXISTS ONLY public.comment DROP CONSTRAINT IF EXISTS comment_issue_id_fkey;
ALTER TABLE IF EXISTS ONLY public.chat_session DROP CONSTRAINT IF EXISTS chat_session_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.chat_session DROP CONSTRAINT IF EXISTS chat_session_runtime_id_fkey;
ALTER TABLE IF EXISTS ONLY public.chat_session DROP CONSTRAINT IF EXISTS chat_session_creator_id_fkey;
ALTER TABLE IF EXISTS ONLY public.chat_session DROP CONSTRAINT IF EXISTS chat_session_agent_id_fkey;
ALTER TABLE IF EXISTS ONLY public.chat_message DROP CONSTRAINT IF EXISTS chat_message_chat_session_id_fkey;
ALTER TABLE IF EXISTS ONLY public.autopilot DROP CONSTRAINT IF EXISTS autopilot_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.autopilot_trigger DROP CONSTRAINT IF EXISTS autopilot_trigger_autopilot_id_fkey;
ALTER TABLE IF EXISTS ONLY public.autopilot_run DROP CONSTRAINT IF EXISTS autopilot_run_trigger_id_fkey;
ALTER TABLE IF EXISTS ONLY public.autopilot_run DROP CONSTRAINT IF EXISTS autopilot_run_task_id_fkey;
ALTER TABLE IF EXISTS ONLY public.autopilot_run DROP CONSTRAINT IF EXISTS autopilot_run_squad_id_fkey;
ALTER TABLE IF EXISTS ONLY public.autopilot_run DROP CONSTRAINT IF EXISTS autopilot_run_issue_id_fkey;
ALTER TABLE IF EXISTS ONLY public.autopilot_run DROP CONSTRAINT IF EXISTS autopilot_run_autopilot_id_fkey;
ALTER TABLE IF EXISTS ONLY public.autopilot DROP CONSTRAINT IF EXISTS autopilot_project_id_fkey;
ALTER TABLE IF EXISTS ONLY public.attachment DROP CONSTRAINT IF EXISTS attachment_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.attachment DROP CONSTRAINT IF EXISTS attachment_issue_id_fkey;
ALTER TABLE IF EXISTS ONLY public.attachment DROP CONSTRAINT IF EXISTS attachment_comment_id_fkey;
ALTER TABLE IF EXISTS ONLY public.attachment DROP CONSTRAINT IF EXISTS attachment_chat_session_id_fkey;
ALTER TABLE IF EXISTS ONLY public.attachment DROP CONSTRAINT IF EXISTS attachment_chat_message_id_fkey;
ALTER TABLE IF EXISTS ONLY public.agent DROP CONSTRAINT IF EXISTS agent_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.agent_task_queue DROP CONSTRAINT IF EXISTS agent_task_queue_trigger_comment_id_fkey;
ALTER TABLE IF EXISTS ONLY public.agent_task_queue DROP CONSTRAINT IF EXISTS agent_task_queue_runtime_id_fkey;
ALTER TABLE IF EXISTS ONLY public.agent_task_queue DROP CONSTRAINT IF EXISTS agent_task_queue_parent_task_id_fkey;
ALTER TABLE IF EXISTS ONLY public.agent_task_queue DROP CONSTRAINT IF EXISTS agent_task_queue_issue_id_fkey;
ALTER TABLE IF EXISTS ONLY public.agent_task_queue DROP CONSTRAINT IF EXISTS agent_task_queue_chat_session_id_fkey;
ALTER TABLE IF EXISTS ONLY public.agent_task_queue DROP CONSTRAINT IF EXISTS agent_task_queue_autopilot_run_id_fkey;
ALTER TABLE IF EXISTS ONLY public.agent_task_queue DROP CONSTRAINT IF EXISTS agent_task_queue_agent_id_fkey;
ALTER TABLE IF EXISTS ONLY public.agent_skill DROP CONSTRAINT IF EXISTS agent_skill_skill_id_fkey;
ALTER TABLE IF EXISTS ONLY public.agent_skill DROP CONSTRAINT IF EXISTS agent_skill_agent_id_fkey;
ALTER TABLE IF EXISTS ONLY public.agent_runtime DROP CONSTRAINT IF EXISTS agent_runtime_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.agent_runtime DROP CONSTRAINT IF EXISTS agent_runtime_owner_id_fkey;
ALTER TABLE IF EXISTS ONLY public.agent DROP CONSTRAINT IF EXISTS agent_runtime_id_fkey;
ALTER TABLE IF EXISTS ONLY public.agent DROP CONSTRAINT IF EXISTS agent_owner_id_fkey;
ALTER TABLE IF EXISTS ONLY public.agent DROP CONSTRAINT IF EXISTS agent_archived_by_fkey;
ALTER TABLE IF EXISTS ONLY public.activity_log DROP CONSTRAINT IF EXISTS activity_log_workspace_id_fkey;
ALTER TABLE IF EXISTS ONLY public.activity_log DROP CONSTRAINT IF EXISTS activity_log_issue_id_fkey;
DROP TRIGGER IF EXISTS trg_tu_dirty_hourly ON public.task_usage;
DROP TRIGGER IF EXISTS trg_issue_project_dirty_hourly ON public.issue;
DROP TRIGGER IF EXISTS trg_issue_delete_dirty_hourly ON public.issue;
DROP TRIGGER IF EXISTS trg_atq_dirty_hourly ON public.agent_task_queue;
DROP INDEX IF EXISTS public.prompt_library_item_workspace_type_idx;
DROP INDEX IF EXISTS public.prompt_library_item_workspace_project_idx;
DROP INDEX IF EXISTS public.prompt_evaluation_asset_workspace_type_idx;
DROP INDEX IF EXISTS public.prompt_evaluation_asset_prompt_idx;
DROP INDEX IF EXISTS public.issue_label_workspace_name_lower_idx;
DROP INDEX IF EXISTS public.idx_webhook_delivery_run;
DROP INDEX IF EXISTS public.idx_webhook_delivery_dedupe;
DROP INDEX IF EXISTS public.idx_webhook_delivery_autopilot;
DROP INDEX IF EXISTS public.idx_user_created_at;
DROP INDEX IF EXISTS public.idx_task_usage_updated_at;
DROP INDEX IF EXISTS public.idx_task_usage_task_id;
DROP INDEX IF EXISTS public.idx_task_usage_hourly_workspace_time;
DROP INDEX IF EXISTS public.idx_task_usage_hourly_workspace_project_time;
DROP INDEX IF EXISTS public.idx_task_usage_hourly_workspace_agent_time;
DROP INDEX IF EXISTS public.idx_task_usage_hourly_runtime_time;
DROP INDEX IF EXISTS public.idx_task_usage_hourly_dirty_enqueued_at;
DROP INDEX IF EXISTS public.idx_task_usage_created_at_legacy;
DROP INDEX IF EXISTS public.idx_task_usage_created_at;
DROP INDEX IF EXISTS public.idx_task_trace_event_workspace_created;
DROP INDEX IF EXISTS public.idx_task_trace_event_task_created;
DROP INDEX IF EXISTS public.idx_task_trace_event_squad_created;
DROP INDEX IF EXISTS public.idx_task_trace_event_issue_created;
DROP INDEX IF EXISTS public.idx_task_trace_event_agent_created;
DROP INDEX IF EXISTS public.idx_task_token_task;
DROP INDEX IF EXISTS public.idx_task_token_hash;
DROP INDEX IF EXISTS public.idx_task_message_task_id_seq;
DROP INDEX IF EXISTS public.idx_sys_cron_exec_running_stale;
DROP INDEX IF EXISTS public.idx_sys_cron_exec_job_plan;
DROP INDEX IF EXISTS public.idx_sys_cron_exec_finished;
DROP INDEX IF EXISTS public.idx_sys_cron_exec_failed_recent;
DROP INDEX IF EXISTS public.idx_squad_workspace_scope;
DROP INDEX IF EXISTS public.idx_squad_workspace;
DROP INDEX IF EXISTS public.idx_squad_sop_step_event_squad_created;
DROP INDEX IF EXISTS public.idx_squad_sop_step_event_run_created;
DROP INDEX IF EXISTS public.idx_squad_sop_step_event_issue_created;
DROP INDEX IF EXISTS public.idx_squad_sop_run_workspace_created;
DROP INDEX IF EXISTS public.idx_squad_sop_run_squad_created;
DROP INDEX IF EXISTS public.idx_squad_sop_run_issue_open;
DROP INDEX IF EXISTS public.idx_squad_sop_run_issue_created;
DROP INDEX IF EXISTS public.idx_squad_member_squad;
DROP INDEX IF EXISTS public.idx_squad_member_entity;
DROP INDEX IF EXISTS public.idx_skill_workspace;
DROP INDEX IF EXISTS public.idx_skill_file_skill;
DROP INDEX IF EXISTS public.idx_runtime_profile_workspace;
DROP INDEX IF EXISTS public.idx_prompt_library_trial_workspace_created;
DROP INDEX IF EXISTS public.idx_prompt_library_trial_prompt_created;
DROP INDEX IF EXISTS public.idx_prompt_library_version_workspace_created;
DROP INDEX IF EXISTS public.idx_prompt_library_version_prompt_version;
DROP INDEX IF EXISTS public.idx_prompt_evaluation_trial_run_case;
DROP INDEX IF EXISTS public.idx_prompt_evaluation_trial_asset_created;
DROP INDEX IF EXISTS public.idx_prompt_evaluation_test_suite_case_workspace_created;
DROP INDEX IF EXISTS public.idx_prompt_evaluation_test_suite_case_asset_index;
DROP INDEX IF EXISTS public.idx_prompt_evaluation_run_workspace_reviewed;
DROP INDEX IF EXISTS public.idx_prompt_evaluation_run_workspace_created;
DROP INDEX IF EXISTS public.idx_prompt_evaluation_run_task;
DROP INDEX IF EXISTS public.idx_prompt_evaluation_run_asset_created;
DROP INDEX IF EXISTS public.idx_prompt_evaluation_optimization_candidate_workspace_created;
DROP INDEX IF EXISTS public.idx_prompt_evaluation_optimization_candidate_run;
DROP INDEX IF EXISTS public.idx_prompt_evaluation_optimization_candidate_prompt;
DROP INDEX IF EXISTS public.idx_prompt_evaluation_evidence_snapshot_workspace_created;
DROP INDEX IF EXISTS public.idx_prompt_evaluation_evidence_snapshot_run_created;
DROP INDEX IF EXISTS public.idx_prompt_evaluation_dimension_score_workspace_created;
DROP INDEX IF EXISTS public.idx_prompt_evaluation_dimension_score_prompt_dimension;
DROP INDEX IF EXISTS public.idx_prompt_evaluation_dimension_score_asset_dimension;
DROP INDEX IF EXISTS public.idx_prompt_evaluation_dataset_version_workspace_created;
DROP INDEX IF EXISTS public.idx_prompt_evaluation_dataset_version_row_version_index;
DROP INDEX IF EXISTS public.idx_prompt_evaluation_dataset_version_row_asset;
DROP INDEX IF EXISTS public.idx_prompt_evaluation_dataset_version_asset_created;
DROP INDEX IF EXISTS public.idx_prompt_evaluation_dataset_row_workspace_created;
DROP INDEX IF EXISTS public.idx_prompt_evaluation_dataset_row_asset_index;
DROP INDEX IF EXISTS public.idx_prompt_evaluation_case_workspace_created;
DROP INDEX IF EXISTS public.idx_prompt_evaluation_case_tags_gin;
DROP INDEX IF EXISTS public.idx_prompt_evaluation_case_stream_updated;
DROP INDEX IF EXISTS public.idx_prompt_evaluation_case_stream_index;
DROP INDEX IF EXISTS public.idx_prompt_evaluation_case_stream_created;
DROP INDEX IF EXISTS public.idx_prompt_evaluation_case_operation_workspace_created;
DROP INDEX IF EXISTS public.idx_prompt_evaluation_case_operation_status_created;
DROP INDEX IF EXISTS public.idx_prompt_evaluation_case_operation_asset_created;
DROP INDEX IF EXISTS public.idx_prompt_evaluation_case_asset_index;
DROP INDEX IF EXISTS public.idx_prompt_evaluation_case_assertion_workspace;
DROP INDEX IF EXISTS public.idx_prompt_evaluation_case_assertion_case;
DROP INDEX IF EXISTS public.idx_prompt_evaluation_case_assertion_asset;
DROP INDEX IF EXISTS public.idx_project_workspace_scope;
DROP INDEX IF EXISTS public.idx_project_workspace_owner_scope;
DROP INDEX IF EXISTS public.idx_project_workspace;
DROP INDEX IF EXISTS public.idx_project_resource_workspace;
DROP INDEX IF EXISTS public.idx_project_resource_project;
DROP INDEX IF EXISTS public.idx_pinned_item_user_ws;
DROP INDEX IF EXISTS public.idx_pat_user;
DROP INDEX IF EXISTS public.idx_pat_token_hash;
DROP INDEX IF EXISTS public.idx_one_pending_task_per_issue_agent;
DROP INDEX IF EXISTS public.idx_member_workspace;
DROP INDEX IF EXISTS public.idx_member_user_workspace;
DROP INDEX IF EXISTS public.idx_lark_user_binding_workspace_open;
DROP INDEX IF EXISTS public.idx_lark_user_binding_user;
DROP INDEX IF EXISTS public.idx_lark_outbound_card_task;
DROP INDEX IF EXISTS public.idx_lark_outbound_card_session;
DROP INDEX IF EXISTS public.idx_lark_installation_workspace;
DROP INDEX IF EXISTS public.idx_lark_installation_lease;
DROP INDEX IF EXISTS public.idx_lark_installation_agent;
DROP INDEX IF EXISTS public.idx_lark_inbound_dedup_received;
DROP INDEX IF EXISTS public.idx_lark_inbound_audit_reason;
DROP INDEX IF EXISTS public.idx_lark_inbound_audit_installation;
DROP INDEX IF EXISTS public.idx_lark_chat_session_binding_session;
DROP INDEX IF EXISTS public.idx_lark_binding_token_installation;
DROP INDEX IF EXISTS public.idx_issue_workspace_scope;
DROP INDEX IF EXISTS public.idx_issue_workspace_owner_scope;
DROP INDEX IF EXISTS public.idx_issue_workspace_number;
DROP INDEX IF EXISTS public.idx_issue_workspace;
DROP INDEX IF EXISTS public.idx_issue_work_started_at;
DROP INDEX IF EXISTS public.idx_issue_work_completed_at;
DROP INDEX IF EXISTS public.idx_issue_subscriber_user;
DROP INDEX IF EXISTS public.idx_issue_status;
DROP INDEX IF EXISTS public.idx_issue_reaction_issue_id;
DROP INDEX IF EXISTS public.idx_issue_pull_request_pr;
DROP INDEX IF EXISTS public.idx_issue_project;
DROP INDEX IF EXISTS public.idx_issue_parent;
DROP INDEX IF EXISTS public.idx_issue_origin;
DROP INDEX IF EXISTS public.idx_issue_metadata_gin;
DROP INDEX IF EXISTS public.idx_issue_first_executed_at;
DROP INDEX IF EXISTS public.idx_issue_assignee;
DROP INDEX IF EXISTS public.idx_inbox_recipient;
DROP INDEX IF EXISTS public.idx_github_pull_request_workspace;
DROP INDEX IF EXISTS public.idx_github_pr_check_suite_aggregate;
DROP INDEX IF EXISTS public.idx_github_pending_check_suite_received_at;
DROP INDEX IF EXISTS public.idx_github_installation_workspace;
DROP INDEX IF EXISTS public.idx_feedback_user_created;
DROP INDEX IF EXISTS public.idx_external_credential_profile_user_provider;
DROP INDEX IF EXISTS public.idx_daemon_token_workspace_daemon;
DROP INDEX IF EXISTS public.idx_daemon_token_hash;
DROP INDEX IF EXISTS public.idx_comment_reaction_comment_id;
DROP INDEX IF EXISTS public.idx_comment_issue_keyset;
DROP INDEX IF EXISTS public.idx_chat_session_workspace;
DROP INDEX IF EXISTS public.idx_chat_session_creator;
DROP INDEX IF EXISTS public.idx_chat_message_session;
DROP INDEX IF EXISTS public.idx_autopilot_workspace;
DROP INDEX IF EXISTS public.idx_autopilot_trigger_webhook_token;
DROP INDEX IF EXISTS public.idx_autopilot_trigger_next_run;
DROP INDEX IF EXISTS public.idx_autopilot_trigger_autopilot;
DROP INDEX IF EXISTS public.idx_autopilot_subscriber_user;
DROP INDEX IF EXISTS public.idx_autopilot_run_status;
DROP INDEX IF EXISTS public.idx_autopilot_run_squad_id;
DROP INDEX IF EXISTS public.idx_autopilot_run_issue;
DROP INDEX IF EXISTS public.idx_autopilot_run_autopilot;
DROP INDEX IF EXISTS public.idx_autopilot_project;
DROP INDEX IF EXISTS public.idx_autopilot_assignee_type_id;
DROP INDEX IF EXISTS public.idx_autopilot_assignee;
DROP INDEX IF EXISTS public.idx_attachment_workspace;
DROP INDEX IF EXISTS public.idx_attachment_issue;
DROP INDEX IF EXISTS public.idx_attachment_comment;
DROP INDEX IF EXISTS public.idx_attachment_chat_session;
DROP INDEX IF EXISTS public.idx_attachment_chat_message;
DROP INDEX IF EXISTS public.idx_agent_workspace;
DROP INDEX IF EXISTS public.idx_agent_task_queue_runtime_pending;
DROP INDEX IF EXISTS public.idx_agent_task_queue_running_started_at;
DROP INDEX IF EXISTS public.idx_agent_task_queue_queued_created_at;
DROP INDEX IF EXISTS public.idx_agent_task_queue_pending;
DROP INDEX IF EXISTS public.idx_agent_task_queue_parent;
DROP INDEX IF EXISTS public.idx_agent_task_queue_issue_id;
DROP INDEX IF EXISTS public.idx_agent_task_queue_claim_candidates;
DROP INDEX IF EXISTS public.idx_agent_task_queue_chat_pending;
DROP INDEX IF EXISTS public.idx_agent_task_queue_agent;
DROP INDEX IF EXISTS public.idx_agent_skill_skill;
DROP INDEX IF EXISTS public.idx_agent_skill_agent;
DROP INDEX IF EXISTS public.idx_agent_runtime_workspace_scope;
DROP INDEX IF EXISTS public.idx_agent_runtime_workspace;
DROP INDEX IF EXISTS public.idx_agent_runtime_status;
DROP INDEX IF EXISTS public.idx_agent_runtime_last_seen_at;
DROP INDEX IF EXISTS public.idx_activity_log_squad_no_action_task;
DROP INDEX IF EXISTS public.idx_activity_log_issue_keyset;
DROP INDEX IF EXISTS public.comment_issue_resolved_at_idx;
DROP INDEX IF EXISTS public.agent_workspace_name_active_unique;
DROP INDEX IF EXISTS public.agent_runtime_workspace_daemon_provider_key;
DROP INDEX IF EXISTS public.agent_runtime_workspace_daemon_profile_key;
DROP INDEX IF EXISTS public.agent_personal_owner_name_active_unique;
DROP INDEX IF EXISTS public.agent_personal_no_owner_name_active_unique;
ALTER TABLE IF EXISTS ONLY public.workspace DROP CONSTRAINT IF EXISTS workspace_slug_key;
ALTER TABLE IF EXISTS ONLY public.workspace DROP CONSTRAINT IF EXISTS workspace_pkey;
ALTER TABLE IF EXISTS ONLY public.webhook_delivery DROP CONSTRAINT IF EXISTS webhook_delivery_pkey;
ALTER TABLE IF EXISTS ONLY public."user" DROP CONSTRAINT IF EXISTS user_pkey;
ALTER TABLE IF EXISTS ONLY public."user" DROP CONSTRAINT IF EXISTS user_account_key;
ALTER TABLE IF EXISTS ONLY public.task_usage_hourly DROP CONSTRAINT IF EXISTS uq_task_usage_hourly_key;
ALTER TABLE IF EXISTS ONLY public.task_usage_hourly_dirty DROP CONSTRAINT IF EXISTS uq_task_usage_hourly_dirty_key;
ALTER TABLE IF EXISTS ONLY public.sys_cron_executions DROP CONSTRAINT IF EXISTS uq_sys_cron_execution;
ALTER TABLE IF EXISTS ONLY public.issue DROP CONSTRAINT IF EXISTS uq_issue_workspace_number;
ALTER TABLE IF EXISTS ONLY public.daemon_connection DROP CONSTRAINT IF EXISTS uq_daemon_agent;
ALTER TABLE IF EXISTS ONLY public.task_usage DROP CONSTRAINT IF EXISTS task_usage_task_id_provider_model_key;
ALTER TABLE IF EXISTS ONLY public.task_usage DROP CONSTRAINT IF EXISTS task_usage_pkey;
ALTER TABLE IF EXISTS ONLY public.task_usage_hourly_rollup_state DROP CONSTRAINT IF EXISTS task_usage_hourly_rollup_state_pkey;
ALTER TABLE IF EXISTS ONLY public.task_trace_event DROP CONSTRAINT IF EXISTS task_trace_event_pkey;
ALTER TABLE IF EXISTS ONLY public.task_token DROP CONSTRAINT IF EXISTS task_token_pkey;
ALTER TABLE IF EXISTS ONLY public.task_message DROP CONSTRAINT IF EXISTS task_message_pkey;
ALTER TABLE IF EXISTS ONLY public.sys_cron_executions DROP CONSTRAINT IF EXISTS sys_cron_executions_pkey;
ALTER TABLE IF EXISTS ONLY public.squad_sop_step_event DROP CONSTRAINT IF EXISTS squad_sop_step_event_pkey;
ALTER TABLE IF EXISTS ONLY public.squad_sop_run DROP CONSTRAINT IF EXISTS squad_sop_run_pkey;
ALTER TABLE IF EXISTS ONLY public.squad DROP CONSTRAINT IF EXISTS squad_pkey;
ALTER TABLE IF EXISTS ONLY public.squad_member DROP CONSTRAINT IF EXISTS squad_member_squad_id_member_type_member_id_key;
ALTER TABLE IF EXISTS ONLY public.squad_member DROP CONSTRAINT IF EXISTS squad_member_pkey;
ALTER TABLE IF EXISTS ONLY public.skill DROP CONSTRAINT IF EXISTS skill_workspace_id_name_key;
ALTER TABLE IF EXISTS ONLY public.skill DROP CONSTRAINT IF EXISTS skill_pkey;
ALTER TABLE IF EXISTS ONLY public.skill_file DROP CONSTRAINT IF EXISTS skill_file_skill_id_path_key;
ALTER TABLE IF EXISTS ONLY public.skill_file DROP CONSTRAINT IF EXISTS skill_file_pkey;
ALTER TABLE IF EXISTS ONLY public.runtime_profile DROP CONSTRAINT IF EXISTS runtime_profile_workspace_id_display_name_key;
ALTER TABLE IF EXISTS ONLY public.runtime_profile DROP CONSTRAINT IF EXISTS runtime_profile_pkey;
ALTER TABLE IF EXISTS ONLY public.prompt_library_version DROP CONSTRAINT IF EXISTS prompt_library_version_unique;
ALTER TABLE IF EXISTS ONLY public.prompt_library_version DROP CONSTRAINT IF EXISTS prompt_library_version_pkey;
ALTER TABLE IF EXISTS ONLY public.prompt_library_trial DROP CONSTRAINT IF EXISTS prompt_library_trial_pkey;
ALTER TABLE IF EXISTS ONLY public.prompt_library_item DROP CONSTRAINT IF EXISTS prompt_library_item_pkey;
ALTER TABLE IF EXISTS ONLY public.prompt_library_item DROP CONSTRAINT IF EXISTS prompt_library_item_name_unique;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_trial DROP CONSTRAINT IF EXISTS prompt_evaluation_trial_pkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_test_suite_case DROP CONSTRAINT IF EXISTS prompt_evaluation_test_suite_case_pkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_test_suite_case DROP CONSTRAINT IF EXISTS prompt_evaluation_test_suite_case_case_unique;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_test_suite_case DROP CONSTRAINT IF EXISTS prompt_evaluation_test_suite_case_asset_index_unique;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_run DROP CONSTRAINT IF EXISTS prompt_evaluation_run_pkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_optimization_candidate DROP CONSTRAINT IF EXISTS prompt_evaluation_optimization_candidate_pkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_evidence_snapshot DROP CONSTRAINT IF EXISTS prompt_evaluation_evidence_snapshot_pkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_dimension_score DROP CONSTRAINT IF EXISTS prompt_evaluation_dimension_score_run_dimension_unique;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_dimension_score DROP CONSTRAINT IF EXISTS prompt_evaluation_dimension_score_pkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_dataset_version DROP CONSTRAINT IF EXISTS prompt_evaluation_dataset_version_unique;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_dataset_version_row DROP CONSTRAINT IF EXISTS prompt_evaluation_dataset_version_row_unique;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_dataset_version_row DROP CONSTRAINT IF EXISTS prompt_evaluation_dataset_version_row_pkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_dataset_version DROP CONSTRAINT IF EXISTS prompt_evaluation_dataset_version_pkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_dataset_row DROP CONSTRAINT IF EXISTS prompt_evaluation_dataset_row_pkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_dataset_row DROP CONSTRAINT IF EXISTS prompt_evaluation_dataset_row_case_unique;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_dataset_row DROP CONSTRAINT IF EXISTS prompt_evaluation_dataset_row_asset_index_unique;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_case DROP CONSTRAINT IF EXISTS prompt_evaluation_case_pkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_case_operation DROP CONSTRAINT IF EXISTS prompt_evaluation_case_operation_pkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_case DROP CONSTRAINT IF EXISTS prompt_evaluation_case_asset_index_unique;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_case_assertion DROP CONSTRAINT IF EXISTS prompt_evaluation_case_assertion_pkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_case_assertion DROP CONSTRAINT IF EXISTS prompt_evaluation_case_assertion_case_index_unique;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_asset DROP CONSTRAINT IF EXISTS prompt_evaluation_asset_pkey;
ALTER TABLE IF EXISTS ONLY public.prompt_evaluation_asset DROP CONSTRAINT IF EXISTS prompt_evaluation_asset_name_unique;
ALTER TABLE IF EXISTS ONLY public.project_resource DROP CONSTRAINT IF EXISTS project_resource_project_id_resource_type_resource_ref_key;
ALTER TABLE IF EXISTS ONLY public.project_resource DROP CONSTRAINT IF EXISTS project_resource_pkey;
ALTER TABLE IF EXISTS ONLY public.project DROP CONSTRAINT IF EXISTS project_pkey;
ALTER TABLE IF EXISTS ONLY public.pinned_item DROP CONSTRAINT IF EXISTS pinned_item_workspace_id_user_id_item_type_item_id_key;
ALTER TABLE IF EXISTS ONLY public.pinned_item DROP CONSTRAINT IF EXISTS pinned_item_pkey;
ALTER TABLE IF EXISTS ONLY public.personal_access_token DROP CONSTRAINT IF EXISTS personal_access_token_pkey;
ALTER TABLE IF EXISTS ONLY public.notification_preference DROP CONSTRAINT IF EXISTS notification_preference_workspace_id_user_id_key;
ALTER TABLE IF EXISTS ONLY public.notification_preference DROP CONSTRAINT IF EXISTS notification_preference_pkey;
ALTER TABLE IF EXISTS ONLY public.member DROP CONSTRAINT IF EXISTS member_workspace_id_user_id_key;
ALTER TABLE IF EXISTS ONLY public.member DROP CONSTRAINT IF EXISTS member_pkey;
ALTER TABLE IF EXISTS ONLY public.lark_user_binding DROP CONSTRAINT IF EXISTS lark_user_binding_pkey;
ALTER TABLE IF EXISTS ONLY public.lark_user_binding DROP CONSTRAINT IF EXISTS lark_user_binding_installation_id_lark_open_id_key;
ALTER TABLE IF EXISTS ONLY public.lark_outbound_card_message DROP CONSTRAINT IF EXISTS lark_outbound_card_message_pkey;
ALTER TABLE IF EXISTS ONLY public.lark_installation DROP CONSTRAINT IF EXISTS lark_installation_workspace_id_agent_id_key;
ALTER TABLE IF EXISTS ONLY public.lark_installation DROP CONSTRAINT IF EXISTS lark_installation_pkey;
ALTER TABLE IF EXISTS ONLY public.lark_installation DROP CONSTRAINT IF EXISTS lark_installation_id_workspace_id_key;
ALTER TABLE IF EXISTS ONLY public.lark_installation DROP CONSTRAINT IF EXISTS lark_installation_app_id_key;
ALTER TABLE IF EXISTS ONLY public.lark_inbound_message_dedup DROP CONSTRAINT IF EXISTS lark_inbound_message_dedup_pkey;
ALTER TABLE IF EXISTS ONLY public.lark_inbound_audit DROP CONSTRAINT IF EXISTS lark_inbound_audit_pkey;
ALTER TABLE IF EXISTS ONLY public.lark_chat_session_binding DROP CONSTRAINT IF EXISTS lark_chat_session_binding_pkey;
ALTER TABLE IF EXISTS ONLY public.lark_chat_session_binding DROP CONSTRAINT IF EXISTS lark_chat_session_binding_installation_id_lark_chat_id_key;
ALTER TABLE IF EXISTS ONLY public.lark_chat_session_binding DROP CONSTRAINT IF EXISTS lark_chat_session_binding_chat_session_id_key;
ALTER TABLE IF EXISTS ONLY public.lark_binding_token DROP CONSTRAINT IF EXISTS lark_binding_token_pkey;
ALTER TABLE IF EXISTS ONLY public.issue_to_label DROP CONSTRAINT IF EXISTS issue_to_label_pkey;
ALTER TABLE IF EXISTS ONLY public.issue_subscriber DROP CONSTRAINT IF EXISTS issue_subscriber_pkey;
ALTER TABLE IF EXISTS ONLY public.issue_reaction DROP CONSTRAINT IF EXISTS issue_reaction_pkey;
ALTER TABLE IF EXISTS ONLY public.issue_reaction DROP CONSTRAINT IF EXISTS issue_reaction_issue_id_actor_type_actor_id_emoji_key;
ALTER TABLE IF EXISTS ONLY public.issue_pull_request DROP CONSTRAINT IF EXISTS issue_pull_request_pkey;
ALTER TABLE IF EXISTS ONLY public.issue DROP CONSTRAINT IF EXISTS issue_pkey;
ALTER TABLE IF EXISTS ONLY public.issue_label DROP CONSTRAINT IF EXISTS issue_label_pkey;
ALTER TABLE IF EXISTS ONLY public.issue_dependency DROP CONSTRAINT IF EXISTS issue_dependency_pkey;
ALTER TABLE IF EXISTS ONLY public.inbox_item DROP CONSTRAINT IF EXISTS inbox_item_pkey;
ALTER TABLE IF EXISTS ONLY public.github_pull_request DROP CONSTRAINT IF EXISTS github_pull_request_workspace_id_repo_owner_repo_name_pr_nu_key;
ALTER TABLE IF EXISTS ONLY public.github_pull_request DROP CONSTRAINT IF EXISTS github_pull_request_pkey;
ALTER TABLE IF EXISTS ONLY public.github_pull_request_check_suite DROP CONSTRAINT IF EXISTS github_pull_request_check_suite_pkey;
ALTER TABLE IF EXISTS ONLY public.github_pending_installation DROP CONSTRAINT IF EXISTS github_pending_installation_pkey;
ALTER TABLE IF EXISTS ONLY public.github_pending_check_suite DROP CONSTRAINT IF EXISTS github_pending_check_suite_pkey;
ALTER TABLE IF EXISTS ONLY public.github_installation DROP CONSTRAINT IF EXISTS github_installation_pkey;
ALTER TABLE IF EXISTS ONLY public.github_installation DROP CONSTRAINT IF EXISTS github_installation_installation_id_key;
ALTER TABLE IF EXISTS ONLY public.feedback DROP CONSTRAINT IF EXISTS feedback_pkey;
ALTER TABLE IF EXISTS ONLY public.external_credential_profile DROP CONSTRAINT IF EXISTS external_credential_profile_user_id_provider_name_key;
ALTER TABLE IF EXISTS ONLY public.external_credential_profile DROP CONSTRAINT IF EXISTS external_credential_profile_pkey;
ALTER TABLE IF EXISTS ONLY public.daemon_token DROP CONSTRAINT IF EXISTS daemon_token_pkey;
ALTER TABLE IF EXISTS ONLY public.daemon_connection DROP CONSTRAINT IF EXISTS daemon_connection_pkey;
ALTER TABLE IF EXISTS ONLY public.comment_reaction DROP CONSTRAINT IF EXISTS comment_reaction_pkey;
ALTER TABLE IF EXISTS ONLY public.comment_reaction DROP CONSTRAINT IF EXISTS comment_reaction_comment_id_actor_type_actor_id_emoji_key;
ALTER TABLE IF EXISTS ONLY public.comment DROP CONSTRAINT IF EXISTS comment_pkey;
ALTER TABLE IF EXISTS ONLY public.chat_session DROP CONSTRAINT IF EXISTS chat_session_pkey;
ALTER TABLE IF EXISTS ONLY public.chat_message DROP CONSTRAINT IF EXISTS chat_message_pkey;
ALTER TABLE IF EXISTS ONLY public.autopilot_trigger DROP CONSTRAINT IF EXISTS autopilot_trigger_pkey;
ALTER TABLE IF EXISTS ONLY public.autopilot_subscriber DROP CONSTRAINT IF EXISTS autopilot_subscriber_pkey;
ALTER TABLE IF EXISTS ONLY public.autopilot_run DROP CONSTRAINT IF EXISTS autopilot_run_pkey;
ALTER TABLE IF EXISTS ONLY public.autopilot DROP CONSTRAINT IF EXISTS autopilot_pkey;
ALTER TABLE IF EXISTS ONLY public.attachment DROP CONSTRAINT IF EXISTS attachment_pkey;
ALTER TABLE IF EXISTS ONLY public.agent_task_queue DROP CONSTRAINT IF EXISTS agent_task_queue_pkey;
ALTER TABLE IF EXISTS ONLY public.agent_skill DROP CONSTRAINT IF EXISTS agent_skill_pkey;
ALTER TABLE IF EXISTS ONLY public.agent_runtime DROP CONSTRAINT IF EXISTS agent_runtime_pkey;
ALTER TABLE IF EXISTS ONLY public.agent DROP CONSTRAINT IF EXISTS agent_pkey;
ALTER TABLE IF EXISTS ONLY public.activity_log DROP CONSTRAINT IF EXISTS activity_log_pkey;
DROP TABLE IF EXISTS public.workspace;
DROP TABLE IF EXISTS public.webhook_delivery;
DROP TABLE IF EXISTS public."user";
DROP TABLE IF EXISTS public.task_usage_hourly_rollup_state;
DROP TABLE IF EXISTS public.task_usage_hourly_dirty;
DROP TABLE IF EXISTS public.task_usage_hourly;
DROP TABLE IF EXISTS public.task_usage;
DROP TABLE IF EXISTS public.task_trace_event;
DROP TABLE IF EXISTS public.task_token;
DROP TABLE IF EXISTS public.task_message;
DROP TABLE IF EXISTS public.sys_cron_executions;
DROP TABLE IF EXISTS public.squad_sop_step_event;
DROP TABLE IF EXISTS public.squad_sop_run;
DROP TABLE IF EXISTS public.squad_member;
DROP TABLE IF EXISTS public.squad;
DROP TABLE IF EXISTS public.skill_file;
DROP TABLE IF EXISTS public.skill;
DROP TABLE IF EXISTS public.runtime_profile;
DROP TABLE IF EXISTS public.prompt_library_trial;
DROP TABLE IF EXISTS public.prompt_library_version;
DROP TABLE IF EXISTS public.prompt_library_item;
DROP TABLE IF EXISTS public.prompt_evaluation_trial;
DROP TABLE IF EXISTS public.prompt_evaluation_test_suite_case;
DROP TABLE IF EXISTS public.prompt_evaluation_run;
DROP TABLE IF EXISTS public.prompt_evaluation_optimization_candidate;
DROP TABLE IF EXISTS public.prompt_evaluation_evidence_snapshot;
DROP TABLE IF EXISTS public.prompt_evaluation_dimension_score;
DROP TABLE IF EXISTS public.prompt_evaluation_dataset_version_row;
DROP TABLE IF EXISTS public.prompt_evaluation_dataset_version;
DROP TABLE IF EXISTS public.prompt_evaluation_dataset_row;
DROP TABLE IF EXISTS public.prompt_evaluation_case_operation;
DROP TABLE IF EXISTS public.prompt_evaluation_case_assertion;
DROP TABLE IF EXISTS public.prompt_evaluation_case;
DROP TABLE IF EXISTS public.prompt_evaluation_asset;
DROP TABLE IF EXISTS public.project_resource;
DROP TABLE IF EXISTS public.project;
DROP TABLE IF EXISTS public.pinned_item;
DROP TABLE IF EXISTS public.personal_access_token;
DROP TABLE IF EXISTS public.notification_preference;
DROP TABLE IF EXISTS public.member;
DROP TABLE IF EXISTS public.lark_user_binding;
DROP TABLE IF EXISTS public.lark_outbound_card_message;
DROP TABLE IF EXISTS public.lark_installation;
DROP TABLE IF EXISTS public.lark_inbound_message_dedup;
DROP TABLE IF EXISTS public.lark_inbound_audit;
DROP TABLE IF EXISTS public.lark_chat_session_binding;
DROP TABLE IF EXISTS public.lark_binding_token;
DROP TABLE IF EXISTS public.issue_to_label;
DROP TABLE IF EXISTS public.issue_subscriber;
DROP TABLE IF EXISTS public.issue_reaction;
DROP TABLE IF EXISTS public.issue_pull_request;
DROP TABLE IF EXISTS public.issue_label;
DROP TABLE IF EXISTS public.issue_dependency;
DROP TABLE IF EXISTS public.issue;
DROP TABLE IF EXISTS public.inbox_item;
DROP TABLE IF EXISTS public.github_pull_request_check_suite;
DROP TABLE IF EXISTS public.github_pull_request;
DROP TABLE IF EXISTS public.github_pending_installation;
DROP TABLE IF EXISTS public.github_pending_check_suite;
DROP TABLE IF EXISTS public.github_installation;
DROP TABLE IF EXISTS public.feedback;
DROP TABLE IF EXISTS public.external_credential_profile;
DROP TABLE IF EXISTS public.daemon_token;
DROP TABLE IF EXISTS public.daemon_connection;
DROP TABLE IF EXISTS public.comment_reaction;
DROP TABLE IF EXISTS public.comment;
DROP TABLE IF EXISTS public.chat_session;
DROP TABLE IF EXISTS public.chat_message;
DROP TABLE IF EXISTS public.autopilot_trigger;
DROP TABLE IF EXISTS public.autopilot_subscriber;
DROP TABLE IF EXISTS public.autopilot_run;
DROP TABLE IF EXISTS public.autopilot;
DROP TABLE IF EXISTS public.attachment;
DROP TABLE IF EXISTS public.agent_task_queue;
DROP TABLE IF EXISTS public.agent_skill;
DROP TABLE IF EXISTS public.agent_runtime;
DROP TABLE IF EXISTS public.agent;
DROP TABLE IF EXISTS public.activity_log;
DROP FUNCTION IF EXISTS public.task_usage_hourly_rollup_lag_seconds();
DROP FUNCTION IF EXISTS public.task_usage_hour_bucket(ts timestamp with time zone);
DROP FUNCTION IF EXISTS public.rollup_task_usage_hourly_window(p_from timestamp with time zone, p_to timestamp with time zone);
DROP FUNCTION IF EXISTS public.rollup_task_usage_hourly();
DROP FUNCTION IF EXISTS public.prune_task_usage_hourly_dirty(p_retention interval);
DROP FUNCTION IF EXISTS public.enqueue_task_usage_hourly_dirty_for_tu();
DROP FUNCTION IF EXISTS public.enqueue_task_usage_hourly_dirty_for_issue_project();
DROP FUNCTION IF EXISTS public.enqueue_task_usage_hourly_dirty_for_issue_delete();
DROP FUNCTION IF EXISTS public.enqueue_task_usage_hourly_dirty_for_atq();
DROP EXTENSION IF EXISTS pgcrypto;

SELECT pg_catalog.set_config('search_path', 'public', false);
