CREATE TABLE IF NOT EXISTS task_trace_event (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    workspace_id uuid NOT NULL,
    task_id uuid NOT NULL,
    issue_id uuid,
    agent_id uuid NOT NULL,
    runtime_id uuid,
    squad_id uuid,
    project_id uuid,
    source text DEFAULT '' NOT NULL,
    event_type text NOT NULL,
    event_name text NOT NULL,
    status text DEFAULT '' NOT NULL,
    attempt integer DEFAULT 1 NOT NULL,
    duration_ms bigint,
    queue_wait_ms bigint,
    run_ms bigint,
    total_ms bigint,
    provider text DEFAULT '' NOT NULL,
    model text DEFAULT '' NOT NULL,
    input_tokens bigint DEFAULT 0 NOT NULL,
    output_tokens bigint DEFAULT 0 NOT NULL,
    cache_read_tokens bigint DEFAULT 0 NOT NULL,
    cache_write_tokens bigint DEFAULT 0 NOT NULL,
    failure_reason text DEFAULT '' NOT NULL,
    error_type text DEFAULT '' NOT NULL,
    trigger_comment_id uuid,
    autopilot_run_id uuid,
    chat_session_id uuid,
    metadata jsonb DEFAULT '{}' NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT task_trace_event_metadata_is_object CHECK (jsonb_typeof(metadata) = 'object')
);
