package handler

import (
	"fmt"
	"strings"

	"github.com/multica-ai/multica/server/internal/service"
)

// mikaOnboardingOpenings is Mika's first reply, written by the product rather
// than generated by an agent run (MUL-5827).
//
// It reads as an agent's words, but it is the least agent-dependent output in
// the product: it consults no workspace state, calls no tool, and makes no
// decision. The multica-onboarding skill already pinned it to four beats under
// a length budget, so an agent run was paying a runtime cold start and two
// model round trips to render something already decided — while the member
// watched a spinner, and a failed run greeted them with an error bubble.
//
// The four beats, in order, are load-bearing; keep them when editing:
//
//  1. what Multica is, in one sentence,
//  2. who Mika is to this member,
//  3. what happens next,
//  4. the bridge to the starter cards rendered underneath.
//
// Deliberately NOT varied by role or use case. Seven use cases across four
// languages is a copy matrix nobody can keep coherent, and the questionnaire
// still reaches the model — it rides the kickoff into the member's first real
// turn, which is where tailoring actually pays. Nor is it varied by anything
// the member did in another workspace: every workspace opens from scratch.
//
// %[1]s is the workspace name, %[2]s Mika's display name. Both are
// owner-editable, so both are arguments and never part of the format string.
const mikaOnboardingOpening = `你好，欢迎来到 %[1]s。Multica 是一个人和 AI 智能体通过任务一起把事情做完的工作区。

我是 %[2]s，这里的 Chief of Staff。我负责把事情理清楚、找到合适的智能体接手，也是你随时可以开口的第一站。

接下来是这样：你说一个目标，我把它变成一个任务，交给合适的智能体开始跑，你能看着它推进。

从下面选一个开始，或者直接告诉我你现在想做成什么。`

// buildMikaOnboardingOpening renders the Chinese opening. The name falls back
// to the product default when an owner has blanked
// it, because the sentence is about who is speaking and reads as broken without
// one.
func buildMikaOnboardingOpening(agentName, workspaceName string) string {
	name := strings.TrimSpace(agentName)
	if name == "" {
		name = service.MikaDefaultName
	}
	return fmt.Sprintf(
		mikaOnboardingOpening,
		escapeMarkdownInline(strings.TrimSpace(workspaceName)),
		escapeMarkdownInline(name),
	)
}

// escapeMarkdownInline neutralizes the inline markdown metacharacters in
// member-authored names before they are interpolated into rendered copy. Chat
// renders assistant content as markdown, so a workspace called `**Ops**` would
// otherwise bold part of Mika's first sentence, and one containing a backtick
// would open a code span that swallows the rest of the line.
//
// Backslash goes first so it never double-escapes an escape this adds. Only
// inline constructs are covered: the names are interpolated mid-sentence, never
// at the start of a line, so block markers like `#` and `-` are inert.
var markdownInlineEscaper = strings.NewReplacer(
	`\`, `\\`,
	"`", "\\`",
	`*`, `\*`,
	`_`, `\_`,
	`~`, `\~`,
	`[`, `\[`,
	`]`, `\]`,
	`<`, `\<`,
)

func escapeMarkdownInline(s string) string {
	return markdownInlineEscaper.Replace(s)
}
